name: Tests

on: [push]

jobs:
  meta-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3.2.0

      - name: install Ruby
        uses: ruby/setup-ruby@v1

      - run: ./bin/dottie tests/meta/

  example-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3.2.0

      - name: install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: install Ruby
        uses: ruby/setup-ruby@v1

      - run: ./bin/dottie tests/example/

  xfail-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3.2.0

      - name: install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: install Ruby
        uses: ruby/setup-ruby@v1

      - run: '! ./bin/dottie xfail-tests/'
