name: Tests

on: [push]

jobs:
  dot-t-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.4]
        ruby-version: [2.7]

    steps:
      - uses: actions/checkout@v2

      - name: install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: gem install bundler

      - run: ./bin/dottie
